# Generated by Django 3.1.6 on 2021-07-15 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Анонс')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
