# Generated by Django 3.2.9 on 2021-12-09 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер аудитории')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитория',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедра',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование дня')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'День недели',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='FormOfEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(blank=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование формы обучения')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='KindSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа')),
            ],
            options={
                'verbose_name': 'Тип предмета',
                'verbose_name_plural': 'Тип предмета',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Расписание обновится в течении 10 минут', null=True, upload_to='schedule/', verbose_name='Файл расписания')),
                ('default_value', models.BooleanField(default=False, verbose_name='Заполнить статические значения')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время загрузки')),
            ],
            options={
                'verbose_name': 'Файл расписания',
                'verbose_name_plural': 'Файлы расписания',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмет',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппа',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='ParityWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование четности')),
            ],
            options={
                'verbose_name': 'Четность недели',
                'verbose_name_plural': 'Четность недели',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Время занятия')),
            ],
            options={
                'verbose_name': 'Время занятия',
                'verbose_name_plural': 'Время занятия',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='LevelOfEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование уровня образования')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'unique_together': {('name', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.audience', verbose_name='Аудитория')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.chair', verbose_name='Кафедра')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.dayofweek', verbose_name='День недели')),
                ('form_of_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.formofeducation', verbose_name='Форма обучения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.kindsubject', verbose_name='Тип предмета')),
                ('level_of_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.levelofeducation', verbose_name='Уровень обучения')),
                ('order_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.orderlesson', verbose_name='Время занятия')),
                ('parity_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.parityweek', verbose_name='Четность недели')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subgroup', verbose_name='Подгруппа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
